---
name: "Publish GitHub Action"

on:
  push:
    branches:    
      - master
      - main

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0

      - name: Publish
        uses: tgymnich/publish-github-action@v1.2.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
